GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/63473dcda6d3f00ccc882935
###
GET http://localhost:3001/api/persons/1000
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name":"cuco",
    "number":1234
}
###
DELETE http://localhost:3001/api/persons/1
###
DELETE http://localhost:3001/api/persons/13
